// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyHabits.Data;

#nullable disable

namespace MyHabits.Migrations
{
    [DbContext(typeof(MyHabitsContext))]
    [Migration("20230810052707_ListFixed1")]
    partial class ListFixed1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyHabits.Models.DayOfHabit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HabitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("_if_action")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.ToTable("DayOfHabit");
                });

            modelBuilder.Entity("MyHabits.Models.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("_date_of_start")
                        .HasColumnType("datetime2");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Habit");
                });

            modelBuilder.Entity("MyHabits.Models.DayOfHabit", b =>
                {
                    b.HasOne("MyHabits.Models.Habit", null)
                        .WithMany("_registered_actions")
                        .HasForeignKey("HabitId");
                });

            modelBuilder.Entity("MyHabits.Models.Habit", b =>
                {
                    b.Navigation("_registered_actions");
                });
#pragma warning restore 612, 618
        }
    }
}
